version: '3.8'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: aperisolve_web
    volumes:
      - aperisolve-data:/app/static/uploads
    ports:
      - "8088:8088"
    env_file:
      - .env
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aperisolve_back
    volumes:
      - aperisolve-data:/app/uploads
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    command: mongod --auth
    env_file:
      - .env
    volumes:
      - aperisolve-db:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  aperisolve-data:
  aperisolve-db:

networks:
  default:
